service: pruebasDeConcepto
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 60
  region: us-east-2

plugins:
  - serverless-offline

functions:
  pokemon:
    handler: src/Pokemon/controllers/pokemonController.pokemon
    events:
      - http:
          path: pokemon/buscar
          method: get
          request:
            parameters:
              querystrings:
                type: false
                evolutionPhase: false
                generation: false
                page: false
